# Generated by Django 6.0.1 on 2026-01-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_cow_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('quantity_in_liters', models.DecimalField(decimal_places=2, help_text='Milk produced in litres', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='accounts.cow')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milk Record',
                'verbose_name_plural': 'Milk Records',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('cow', 'date', 'session')},
            },
        ),
    ]
