# Generated by Django 6.0.1 on 2026-01-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_chatsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('afternoon', 'Afternoon')], max_length=10),
        ),
    ]
