# Generated by Django 6.0.1 on 2026-01-13 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
