# Generated by Django 6.0.1 on 2026-01-26 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cow_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='is_pregnant',
        ),
        migrations.AddField(
            model_name='cow',
            name='current_lactation_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='status',
            field=models.CharField(choices=[('heifer', 'Heifer'), ('lactating', 'Active Milker'), ('dry', 'Dry Milker')], default='heifer', max_length=20),
        ),
        migrations.AlterField(
            model_name='cow',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='BreedingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('natural', 'Natural'), ('ai', 'AI')], max_length=20)),
                ('date_bred', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_events', to='accounts.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('expected_calving_date', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('aborted', 'Aborted')], max_length=20)),
                ('breeding_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.breedingevent')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cow')),
            ],
        ),
    ]
