# production/utils/pdf.py
import os
from datetime import date
from decimal import Decimal

from django.conf import settings
from django.db.models import Sum

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart

from production.models import MilkRecord
from accounts.models import Cow


class MilkProductionPDFReport:
    """
    Generates a branded, analytical milk production PDF report
    suitable for WhatsApp delivery.
    """

    def __init__(self, farm):
        self.farm = farm
        self.today = date.today()
        self.styles = getSampleStyleSheet()

        self.file_path = os.path.join(
            settings.MEDIA_ROOT,
            f"milk_report_farm_{farm.id}_{self.today}.pdf"
        )

    # ==================================================
    # 📊 Data aggregation
    # ==================================================
    def _get_totals(self):
        totals = (
            MilkRecord.objects
            .filter(cow__farm=self.farm, date=self.today)
            .values("session")
            .annotate(total=Sum("quantity_in_liters"))
        )

        morning = sum(
            r["total"] for r in totals if r["session"] == MilkRecord.MORNING
        ) or Decimal("0")

        evening = sum(
            r["total"] for r in totals if r["session"] == MilkRecord.EVENING
        ) or Decimal("0")

        return morning, evening, morning + evening

    # ==================================================
    # 📈 Chart
    # ==================================================
    def _build_chart(self, morning, evening):
        drawing = Drawing(400, 200)

        chart = VerticalBarChart()
        chart.data = [[float(morning), float(evening)]]
        chart.categoryAxis.categoryNames = ["Morning", "Evening"]
        chart.valueAxis.valueMin = 0
        chart.barWidth = 40
        chart.x = 50
        chart.y = 50
        chart.height = 100
        chart.width = 300

        drawing.add(chart)
        return drawing

    # ==================================================
    # 🐄 Table
    # ==================================================
    def _build_table(self):
        records = (
            MilkRecord.objects
            .filter(cow__farm=self.farm, date=self.today)
            .select_related("cow")
        )

        table_data = [
            ["Cow Tag", "Session", "Milk (L)"]
        ]

        for r in records:
            table_data.append([
                r.cow.tag_number,
                r.session.capitalize(),
                str(r.quantity_in_liters)
            ])

        table = Table(table_data, colWidths=[6*cm, 4*cm, 4*cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
            ("FONT", (0,0), (-1,0), "Helvetica-Bold"),
            ("GRID", (0,0), (-1,-1), 1, colors.grey),
            ("ALIGN", (1,1), (-1,-1), "CENTER"),
        ]))

        return table

    # ==================================================
    # 🖨️ Footer
    # ==================================================
    def _footer(self, canvas, doc):
        canvas.setFont("Helvetica", 9)
        canvas.drawString(
            2*cm, 1.2*cm,
            "Generated by Farmgate • Confidential"
        )

    # ==================================================
    # 📄 Build PDF
    # ==================================================
    def generate(self):
        doc = SimpleDocTemplate(
            self.file_path,
            pagesize=A4
        )

        elements = []

        # Logo (optional)
        logo_path = os.path.join(settings.BASE_DIR, "static/logo.png")
        if os.path.exists(logo_path):
            elements.append(
                Image(logo_path, width=4*cm, height=4*cm)
            )

        elements.append(Spacer(1, 12))

        # Header
        elements.append(
            Paragraph(
                f"<b>Milk Production Report</b><br/>"
                f"{self.farm.name}<br/>"
                f"{self.today}",
                self.styles["Title"]
            )
        )

        elements.append(Spacer(1, 16))

        # Summary
        morning, evening, total = self._get_totals()

        elements.append(
            Paragraph(
                f"<b>Summary</b><br/>"
                f"Morning: {morning} L<br/>"
                f"Evening: {evening} L<br/>"
                f"<b>Total: {total} L</b>",
                self.styles["Normal"]
            )
        )

        elements.append(Spacer(1, 20))

        # Chart
        elements.append(self._build_chart(morning, evening))

        elements.append(Spacer(1, 24))

        # Table
        elements.append(
            Paragraph("<b>Per-Cow Breakdown</b>", self.styles["Heading2"])
        )
        elements.append(Spacer(1, 8))
        elements.append(self._build_table())

        # Build
        doc.build(
            elements,
            onFirstPage=self._footer,
            onLaterPages=self._footer
        )

        return self.file_path
